config/routes.rb
SsoRws::Application.routes.draw do
  devise_for :system_users, controllers: { :sessions => "system_user_sessions", :registration => "system_user_registrations" }, only: :sessions

  namespace :ldap do
    get :new
    post :login
  end

  namespace :saml do
    get :new
    post :acs
    get :metadata
    get :logout
  end

  namespace :gapi do
    get :new
    post :login
  end

  namespace :ldap_auth do
    get :new
    post :create
  end

  namespace :gapi_auth do
    get :new
    post :create
  end

  devise_scope :system_user do
    root :to => "system_user_sessions#new", :as => :app_root
    #root to: 'dashboard#home', :as => :home_root
    get "/login" => "system_user_sessions#new", :as => :login
    post '/login' => 'system_user_sessions#create'
    get "/logout" => "system_user_sessions#destroy", :as => :logout
    post "/passwords" => "system_user_registrations#update"
    get "/register" => "system_user_registrations#new", :as => :new_system_user_registration
    post "/register" => "system_user_registrations#create"
    get "/passwords" => "system_user_registrations#edit", :as => :edit_system_user_passwords
  end

  get "/app_login" => "internal/system_user_sessions#login"
  get "/app_logout" => "internal/system_user_sessions#logout"
  get "/ssrs_login" => "internal/system_user_sessions#ssrs_login"
  get "/second_authorize" => "internal/authorization#second_authorize"
  post "/user/get_info" => "internal/system_users#get_info"
  post "/user/validate_permission" => "internal/system_users#validate_permission"
  post "/usdm/login" => "internal/usdm_users#login"
  post "/usdm/get_info" => "internal/usdm_users#get_info"
  post "/usdm/validate_permission" => "internal/usdm_users#validate_permission"
  post "/usdm/change_password" => "internal/usdm_users#change_password"

  root :to => 'dashboard#home', :as => :root
  get 'home' => 'dashboard#home', :as => :home_root
  get 'user_management' => 'dashboard#user_management', :as => :user_management_root
  get 'role_management' => 'dashboard#role_management', :as => :role_management_root
  get 'domain_management' => 'dashboard#domain_management', :as => :domain_management_root

  resources :domains,  :except => [:destroy, :show]
  resources :domain_licensees, :only => [:index, :create] do
    collection do
      get 'get_casinos'
      post 'remove'
    end
  end

  get '/system_users/export' => 'system_users#export'
  get '/roles/export' => 'roles#export'
  get '/system_users/create_system_user_message' => 'system_users#create_system_user_message', as: :create_system_user_message
  resources :roles, :only => [:index, :show] do
    collection do
      post 'upload'
      post 'check_version'
    end
  end

  resources :system_users, :only => [:index, :show, :new, :create] do
    member do
      get 'edit_roles'
      post 'update_roles'
      post 'inactive'
    end
  end

  resources :change_logs, :only => [:index] do
    collection do
      get 'create_system_user'
      get 'inactive_system_user'
      get 'index_edit_role'
      get 'create_domain_licensee'
      get 'index_domain_ldap'
      get 'index_upload_role'
    end
  end

  resources :dashboard, :only => [:index] do
    collection do
      get 'home'
      get 'user_management'
      get 'role_management'
    end
  end

  resources :audit_logs, :only => [:show] do
    match 'search', :via => [:get, :post], on: :collection
  end

  resources :login_histories, :only => [:index]

  namespace :excels do
    get 'create_system_user_log'
    get 'login_history'
    get 'system_user_log'
  end

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

#  match "/404" => "errors#not_found"
  match "/401" => "application#handle_unauthorize"
#  match "/500" => "errors#exception"

  # Catch routing error here
  match '*unmatched', :to => 'application#handle_route_not_found', via: :get
end

app/views/layouts/user_management/_left_panel.html.erb
<!-- Left panel : Navigation area -->
    <!-- Note: This width of the aside area can be adjusted through LESS variables -->
    <aside id="left-panel">

      <!-- NAVIGATION : This navigation is also responsive

      To make this navigation dynamic please make sure to link the node
      (the reference to the nav > ul) after page load. Or the navigation
      will not initialize.
      -->
      <nav>
        <!-- NOTE: Notice the gaps after each icon usage <i></i>..
        Please note that these links work a bit different than
        traditional href="" links. See documentation for details.
        -->

      <% if policy(:system_user).index? %>
        <ul>
          <li id="nav_dashboard">
            <%= link_to user_management_root_path, :title => t("general.dashboard"), :remote => true do %>
              <i class="fa fa-lg fa-fw fa fa-home"></i> <span class="menu-item-parent"><%= t("general.dashboard") %></span>
            <% end %>
          </li>
          <% if policy(:system_user).new? %>
            <li id="nav_create_system_user">
              <%= link_to new_system_user_path, :title => t("user.create_system_user"), :remote => true do %>
                <i class="fa fa-lg fa-fw fa fa-edit"></i> <span class="menu-item-parent"><%= t("user.create_system_user") %></span>
              <% end %>
            </li>
          <% end %>
          <% if policy(:login_history).list? %>
            <li id="nav_list_login_histories">
              <%= link_to login_histories_path, :title => t("login_history.list"), :remote => true do %>
                <i class="fa fa-lg fa-fw fa fa-history"></i> <span class="menu-item-parent"><%= t("login_history.list") %></span>
              <% end %>
            </li>
          <% end %>
          <li id="nav_list_system_users">
            <%= link_to system_users_path, :title => t("user.list_users"), :remote => true do %>
              <i class="fa fa-lg fa-fw fa fa-list"></i> <span class="menu-item-parent"><%= t("user.list_users") %></span>
            <% end %>
          </li>
        </ul>
      <% end %>
      </nav>
      <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
      </span>

    </aside>
    <!-- END NAVIGATION -->