config/routes.rb
SsoRws::Application.routes.draw do
  devise_for :system_users, controllers: { :sessions => "system_user_sessions", :registration => "system_user_registrations" }, only: :sessions

  namespace :ldap do
    get :new
    post :login
  end

  namespace :saml do
    get :new
    post :acs
    get :metadata
    get :logout
  end

  namespace :gapi do
    get :new
    post :login
  end

  namespace :ldap_auth do
    get :new
    post :create
  end

  namespace :gapi_auth do
    get :new
    post :create
  end

  devise_scope :system_user do
    root :to => "system_user_sessions#new", :as => :app_root
    #root to: 'dashboard#home', :as => :home_root
    get "/login" => "system_user_sessions#new", :as => :login
    post '/login' => 'system_user_sessions#create'
    get "/logout" => "system_user_sessions#destroy", :as => :logout
    post "/passwords" => "system_user_registrations#update"
    get "/register" => "system_user_registrations#new", :as => :new_system_user_registration
    post "/register" => "system_user_registrations#create"
    get "/passwords" => "system_user_registrations#edit", :as => :edit_system_user_passwords
  end

  get "/app_login" => "internal/system_user_sessions#login"
  get "/app_logout" => "internal/system_user_sessions#logout"
  get "/ssrs_login" => "internal/system_user_sessions#ssrs_login"
  get "/second_authorize" => "internal/authorization#second_authorize"
  post "/user/get_info" => "internal/system_users#get_info"
  post "/user/validate_permission" => "internal/system_users#validate_permission"
  post "/usdm/login" => "internal/usdm_users#login"
  post "/usdm/get_info" => "internal/usdm_users#get_info"
  post "/usdm/validate_permission" => "internal/usdm_users#validate_permission"
  post "/usdm/change_password" => "internal/usdm_users#change_password"

  root :to => 'dashboard#home', :as => :root
  get 'home' => 'dashboard#home', :as => :home_root
  get 'user_management' => 'dashboard#user_management', :as => :user_management_root
  get 'role_management' => 'dashboard#role_management', :as => :role_management_root
  get 'domain_management' => 'dashboard#domain_management', :as => :domain_management_root

  resources :domains,  :except => [:destroy, :show]
  resources :domain_licensees, :only => [:index, :create] do
    collection do
      get 'get_casinos'
      post 'remove'
    end
  end

  get '/system_users/export' => 'system_users#export'
  get '/roles/export' => 'roles#export'
  get '/system_users/create_system_user_message' => 'system_users#create_system_user_message', as: :create_system_user_message
  resources :roles, :only => [:index, :show] do
    collection do
      post 'upload'
      post 'check_version'
    end
  end

  resources :system_users, :only => [:index, :show, :new, :create] do
    member do
      get 'edit_roles'
      post 'update_roles'
      post 'inactive'
    end
  end

  resources :change_logs, :only => [:index] do
    collection do
      get 'create_system_user'
      get 'inactive_system_user'
      get 'index_edit_role'
      get 'create_domain_licensee'
      get 'index_domain_ldap'
      get 'index_upload_role'
    end
  end

  resources :dashboard, :only => [:index] do
    collection do
      get 'home'
      get 'user_management'
      get 'role_management'
    end
  end

  resources :audit_logs, :only => [:show] do
    match 'search', :via => [:get, :post], on: :collection
  end

  resources :login_histories, :only => [:index]

  namespace :excels do
    get 'create_system_user_log'
    get 'login_history'
    get 'system_user_log'
  end

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

#  match "/404" => "errors#not_found"
  match "/401" => "application#handle_unauthorize"
#  match "/500" => "errors#exception"

  # Catch routing error here
  match '*unmatched', :to => 'application#handle_route_not_found', via: :get
end

app/views/shared/_date_range_picker.html.erb
                    <div class="col-sm-6">
                      <label><%= t("general.start_time") %></label>
                      <div class="form-group">
                        <div class="input-group">
                          <input class="form-control" name="start_time" id="from" type="text" value="<%=default_start_time%>" placeholder="" autocomplete="off">
                          <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <label><%= t("general.end_time") %></label>
                      <div class="form-group">
                        <div class="input-group">
                          <input class="form-control" name="end_time" id="to" type="text" value="<%=default_end_time%>" placeholder="" autocomplete="off">
                          <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        </div>
                      </div>
                    </div>


                    <script>
                      // Date Range Picker
                      $("#from").datepicker({
                        //defaultDate: "+1w",
                        changeMonth: true,
                        dateFormat: "yy-mm-dd",
                        numberOfMonths: 1,
                        prevText: '<i class="fa fa-chevron-left"></i>',
                        nextText: '<i class="fa fa-chevron-right"></i>',
                        onClose: function (selectedDate) {
                            $("#to").datepicker("option", "minDate", selectedDate);
                        }
                      });
                      $("#to").datepicker({
                        //defaultDate: "+1w",
                        changeMonth: true,
                        dateFormat: "yy-mm-dd",
                        numberOfMonths: 1,
                        prevText: '<i class="fa fa-chevron-left"></i>',
                        nextText: '<i class="fa fa-chevron-right"></i>',
                        onClose: function (selectedDate) {
                            $("#from").datepicker("option", "maxDate", selectedDate);
                        }
                      });
                    </script>

app/views/shared/_datetime_picker.html.erb
                    <section>
                      <label class="label"><%=t("general.start_time") %></label> 
                      <label class="input"> <i class="icon-append fa fa-calendar" data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
                        <input class="form-control" name="start_time" id="datetimepicker" type="text" value='<%=format_time(start_time_default_value)%>'>
                      </label>
                    </section>
                    
                    <script type="text/javascript">
                      $(function() {
                        $('#datetimepicker').datetimepicker({
                          useSeconds: true,
                          format: "YYYY-MM-DD HH:mm:ss"
                        });
                      });
                    </script>

app/views/shared/_error404.html.erb
<style>
  .error-text-2 {
    text-align: center;
    font-size: 700%;
    font-weight: bold;
    font-weight: 100;
    color: #333;
    line-height: 1;
    letter-spacing: -.05em;
    background-image: -webkit-linear-gradient(92deg,#333,#ed1c24);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }
  .particle {
    position: absolute;
    top: 50%;
    left: 50%;
    width: 1rem;
    height: 1rem;
    border-radius: 100%;
    background-color: #ed1c24;
    background-image: -webkit-linear-gradient(rgba(0,0,0,0),rgba(0,0,0,.3) 75%,rgba(0,0,0,0));
    box-shadow: inset 0 0 1px 1px rgba(0,0,0,.25);
  }
  .particle--a {
    -webkit-animation: particle-a 1.4s infinite linear;
    -moz-animation: particle-a 1.4s infinite linear;
    -o-animation: particle-a 1.4s infinite linear;
    animation: particle-a 1.4s infinite linear;
  }
  .particle--b {
    -webkit-animation: particle-b 1.3s infinite linear;
    -moz-animation: particle-b 1.3s infinite linear;
    -o-animation: particle-b 1.3s infinite linear;
    animation: particle-b 1.3s infinite linear;
    background-color: #00A300;
  }
  .particle--c {
    -webkit-animation: particle-c 1.5s infinite linear;
    -moz-animation: particle-c 1.5s infinite linear;
    -o-animation: particle-c 1.5s infinite linear;
    animation: particle-c 1.5s infinite linear;
    background-color: #57889C;
  }@-webkit-keyframes particle-a {
  0% {
  -webkit-transform: translate3D(-3rem,-3rem,0);
  z-index: 1;
  -webkit-animation-timing-function: ease-in-out;
  } 25% {
  width: 1.5rem;
  height: 1.5rem;
  }

  50% {
  -webkit-transform: translate3D(4rem, 3rem, 0);
  opacity: 1;
  z-index: 1;
  -webkit-animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .75rem;
  height: .75rem;
  opacity: .5;
  }

  100% {
  -webkit-transform: translate3D(-3rem,-3rem,0);
  z-index: -1;
  }
  }

  @-moz-keyframes particle-a {
  0% {
  -moz-transform: translate3D(-3rem,-3rem,0);
  z-index: 1;
  -moz-animation-timing-function: ease-in-out;
  }

  25% {
  width: 1.5rem;
  height: 1.5rem;
  }

  50% {
  -moz-transform: translate3D(4rem, 3rem, 0);
  opacity: 1;
  z-index: 1;
  -moz-animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .75rem;
  height: .75rem;
  opacity: .5;
  }

  100% {
  -moz-transform: translate3D(-3rem,-3rem,0);
  z-index: -1;
  }
  }

  @-o-keyframes particle-a {
  0% {
  -o-transform: translate3D(-3rem,-3rem,0);
  z-index: 1;
  -o-animation-timing-function: ease-in-out;
  }

  25% {
  width: 1.5rem;
  height: 1.5rem;
  }

  50% {
  -o-transform: translate3D(4rem, 3rem, 0);
  opacity: 1;
  z-index: 1;
  -o-animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .75rem;
  height: .75rem;
  opacity: .5;
  }

  100% {
  -o-transform: translate3D(-3rem,-3rem,0);
  z-index: -1;
  }
  }

  @keyframes particle-a {
  0% {
  transform: translate3D(-3rem,-3rem,0);
  z-index: 1;
  animation-timing-function: ease-in-out;
  }

  25% {
  width: 1.5rem;
  height: 1.5rem;
  }

  50% {
  transform: translate3D(4rem, 3rem, 0);
  opacity: 1;
  z-index: 1;
  animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .75rem;
  height: .75rem;
  opacity: .5;
  }

  100% {
  transform: translate3D(-3rem,-3rem,0);
  z-index: -1;
  }
  }

  @-webkit-keyframes particle-b {
  0% {
  -webkit-transform: translate3D(3rem,-3rem,0);
  z-index: 1;
  -webkit-animation-timing-function: ease-in-out;
  }

  25% {
  width: 1.5rem;
  height: 1.5rem;
  }

  50% {
  -webkit-transform: translate3D(-3rem, 3.5rem, 0);
  opacity: 1;
  z-index: 1;
  -webkit-animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .5rem;
  height: .5rem;
  opacity: .5;
  }

  100% {
  -webkit-transform: translate3D(3rem,-3rem,0);
  z-index: -1;
  }
  }

  @-moz-keyframes particle-b {
  0% {
  -moz-transform: translate3D(3rem,-3rem,0);
  z-index: 1;
  -moz-animation-timing-function: ease-in-out;
  }

  25% {
  width: 1.5rem;
  height: 1.5rem;
  }

  50% {
  -moz-transform: translate3D(-3rem, 3.5rem, 0);
  opacity: 1;
  z-index: 1;
  -moz-animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .5rem;
  height: .5rem;
  opacity: .5;
  }

  100% {
  -moz-transform: translate3D(3rem,-3rem,0);
  z-index: -1;
  }
  }

  @-o-keyframes particle-b {
  0% {
  -o-transform: translate3D(3rem,-3rem,0);
  z-index: 1;
  -o-animation-timing-function: ease-in-out;
  }

  25% {
  width: 1.5rem;
  height: 1.5rem;
  }

  50% {
  -o-transform: translate3D(-3rem, 3.5rem, 0);
  opacity: 1;
  z-index: 1;
  -o-animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .5rem;
  height: .5rem;
  opacity: .5;
  }

  100% {
  -o-transform: translate3D(3rem,-3rem,0);
  z-index: -1;
  }
  }

  @keyframes particle-b {
  0% {
  transform: translate3D(3rem,-3rem,0);
  z-index: 1;
  animation-timing-function: ease-in-out;
  }

  25% {
  width: 1.5rem;
  height: 1.5rem;
  }

  50% {
  transform: translate3D(-3rem, 3.5rem, 0);
  opacity: 1;
  z-index: 1;
  animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .5rem;
  height: .5rem;
  opacity: .5;
  }

  100% {
  transform: translate3D(3rem,-3rem,0);
  z-index: -1;
  }
  }

  @-webkit-keyframes particle-c {
  0% {
  -webkit-transform: translate3D(-1rem,-3rem,0);
  z-index: 1;
  -webkit-animation-timing-function: ease-in-out;
  }

  25% {
  width: 1.3rem;
  height: 1.3rem;
  }

  50% {
  -webkit-transform: translate3D(2rem, 2.5rem, 0);
  opacity: 1;
  z-index: 1;
  -webkit-animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .5rem;
  height: .5rem;
  opacity: .5;
  }

  100% {
  -webkit-transform: translate3D(-1rem,-3rem,0);
  z-index: -1;
  }
  }

  @-moz-keyframes particle-c {
  0% {
  -moz-transform: translate3D(-1rem,-3rem,0);
  z-index: 1;
  -moz-animation-timing-function: ease-in-out;
  }

  25% {
  width: 1.3rem;
  height: 1.3rem;
  }

  50% {
  -moz-transform: translate3D(2rem, 2.5rem, 0);
  opacity: 1;
  z-index: 1;
  -moz-animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .5rem;
  height: .5rem;
  opacity: .5;
  }

  100% {
  -moz-transform: translate3D(-1rem,-3rem,0);
  z-index: -1;
  }
  }

  @-o-keyframes particle-c {
  0% {
  -o-transform: translate3D(-1rem,-3rem,0);
  z-index: 1;
  -o-animation-timing-function: ease-in-out;
  }

  25% {
  width: 1.3rem;
  height: 1.3rem;
  }

  50% {
  -o-transform: translate3D(2rem, 2.5rem, 0);
  opacity: 1;
  z-index: 1;
  -o-animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .5rem;
  height: .5rem;
  opacity: .5;
  }

  100% {
  -o-transform: translate3D(-1rem,-3rem,0);
  z-index: -1;
  }
  }

  @keyframes particle-c {
  0% {
  transform: translate3D(-1rem,-3rem,0);
  z-index: 1;
  animation-timing-function: ease-in-out;
  }

  25% {
  width: 1.3rem;
  height: 1.3rem;
  }

  50% {
  transform: translate3D(2rem, 2.5rem, 0);
  opacity: 1;
  z-index: 1;
  animation-timing-function: ease-in-out;
  }

  55% {
  z-index: -1;
  }

  75% {
  width: .5rem;
  height: .5rem;
  opacity: .5;
  }

  100% {
  transform: translate3D(-1rem,-3rem,0);
  z-index: -1;
  }
  }
</style>

<!--[if IE 9]>
<style>
.error-text {
  color: #333 !important;
}
.particle {
  display:none;
}
</style>
<![endif]-->
<div class="row">

  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <div class="row">
      <div class="col-sm-12">
        <div class="text-center error-box">
          <h1 class="error-text-2 bounceInDown animated"> Error 404 <span class="particle particle--c"></span><span class="particle particle--a"></span><span class="particle particle--b"></span></h1>
          <h2 class="font-xl"><strong><i class="fa fa-fw fa-warning fa-lg text-warning"></i> Page <u>Not</u> Found</strong></h2>
          <br />
          <p class="lead">
            The page you requested could not be found, either contact your webmaster or try again. Use your browsers <b>Back</b> button to navigate to the page you have prevously come from
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error500.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="row">
      <div class="col-sm-12">
        <div class="text-center error-box">
          <h1 class="error-text tada animated"><i class="fa fa-times-circle text-danger error-icon-shadow"></i> Error 500</h1>
          <h2 class="font-xl"><strong>Oooops, Something went wrong!</strong></h2>
          <br />
          <p class="lead semi-bold">
            <strong>You have experienced a technical error. We apologize.</strong><br><br>
          </p>
          <ul class="error-search text-left font-md">
           <li>
            <%= link_to(@from || home_root_path, :remote => (@from ? true : false)) do %>
              <small>Go back</small>
            <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_page.js.erb
$('div#content').html("<%= escape_javascript(render :partial => "shared/error_page", :formats => [ :html ], :status
=> :not_found) %>");

app/views/shared/_error_page_head.html.erb
  <title><%=t("general.product_name") %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "bootstrap.min", :media => "screen" %>
  <%= stylesheet_link_tag "font-awesome.min", :media => "screen" %>
  <%= stylesheet_link_tag "smartadmin-production.min", :media => "screen" %>
  <%= javascript_include_tag "jquery-rails" %>
  
   <!--[if IE 8]>
  <h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
  <![endif]-->

app/views/shared/_flash_message.html.erb
             <% flash.each do |type, msg| %>
                <!-- only care about notice & alert type-->
                <% next unless type == :success || type == :alert %>
                <%= content_tag :div, :class => "alert #{bootstrap_class_for(type)} fade in" do %>
                  <button class="close" data-dismiss="alert">×</button>
                  <div id="message_content">
                    <!-- %= t(msg) % -->
                    <% if defined?(use_translation) && use_translation %>
                    <%= t(msg) %>
                    <% else %>
                    <%= msg %>
                    <% end %>
                  </div>
                <% end %>
                <!--% flash.clear %-->
              <% end %>

app/views/shared/_flash_message.js.erb
$('div#flash_message').html("<%= escape_javascript(render :partial => "shared/flash_message", :formats => [ :html ] , :layout => nil) %>");

clearFlashMessage();
popFlashMessage();

<% flash.clear %>

app/views/shared/_head.html.erb
  <title><%=t("general.product_name") %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "bootstrap.min", :media => "screen" %>
  <%= stylesheet_link_tag "font-awesome.min", :media => "screen" %>
  <%= stylesheet_link_tag "smartadmin-rtl.min", :media => "screen" %>
  <%= stylesheet_link_tag "smartadmin-production.min", :media => "screen" %>
  <%= stylesheet_link_tag "smartadmin-skins.min", :media => "screen" %>
  <%= stylesheet_link_tag "select2-extend", :media => "screen" %>
  <%= stylesheet_link_tag "bootstrap-datetimepicker", :media => "screen" %>
  <%= stylesheet_link_tag "ap_customize_style.css", :media => "screen" %>
  <%= stylesheet_link_tag "your_style.css", :media => "screen" %>
  <%= javascript_include_tag "jquery-rails" %>


   <!--[if IE 8]>
  <h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
  <![endif]-->

app/views/shared/_header.html.erb
    <!-- ap_header -->
    <header id="header">
      <div id="logo-group">
        <!-- PLACE YOUR LOGO HERE -->
        <!--span id="logo"> <img src="img/logo.png" alt="SmartAdmin"> </span-->
        <span id="logo" style="width: 250px">
          <!--%= image_tag("mylogo.png", alt: "Cirrus") %-->
          <p> <%= t("general.product_portfolio") %> / <%= t("general.product_name") %> </p>
        </span>
        <!-- END LOGO PLACEHOLDER -->

        <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
        <div class="ajax-dropdown">

          <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
          <div class="btn-group btn-group-justified" data-toggle="buttons">
            <label class="btn btn-default">
              <input type="radio" name="activity" id="ajax/notify/mail.html">
              Msgs (14) </label>
            <label class="btn btn-default">
              <input type="radio" name="activity" id="ajax/notify/notifications.html">
              notify (3) </label>
            <label class="btn btn-default">
              <input type="radio" name="activity" id="ajax/notify/tasks.html">
              Tasks (4) </label>
          </div>

          <!-- notification content -->
          <div class="ajax-notifications custom-scroll">

            <div class="alert alert-transparent">
              <h4>Click a button to show messages here</h4>
              This blank page message helps protect your privacy, or you can show the first message here automatically.
            </div>

            <i class="fa fa-lock fa-4x fa-border"></i>

          </div>
          <!-- end notification content -->

          <!-- footer: refresh area -->
          <span> Last updated on: 12/12/2013 9:43AM
            <button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
              <i class="fa fa-refresh"></i>
            </button> </span>
          <!-- end footer -->

        </div>
        <!-- END AJAX-DROPDOWN -->
      </div>

      <!-- #PROJECTS: projects dropdown -->
      <div class="project-context hidden-xs">
        <span class="label"></span>
        <span id="function_dropdown_toggle" class="project-selector dropdown-toggle" data-toggle="dropdown">
        <% case selected_page_tab
          when "home" %>
            <%= t("header.home") %>
          <% when "user_management" %>
            <%= t("header.user_management") %>
          <% when "role_management" %>
            <%= t("header.role_management") %>
          <% when "audit_log" %>
            <%= t("header.audit_log") %>
          <% when "domain_management" %>
            <%= t("header.domain_management") %>
        <% end %>
          <i class="fa fa-angle-down"></i>
        </span>

        <!-- Suggestion: populate this list with fetch and push technique -->
        <ul class="dropdown-menu">
          <li class=<%= selected_page_tab == "home" ? "active" : "" %>>
            <%= link_to "Home", home_root_path, :id => "home_link" %>
          </li>

          <!-- domain_management -->
          <% if policy(:domain).index_domain_ldap? || policy(:domain).index_domain_licensee? %>
            <li class=<%= selected_page_tab == "domain_management" ? "active" : "" %>>
              <%= link_to t("header.domain_management"), domain_management_root_path, :id => "domain_management_link" %>
            </li>
          <% end %>

          <% if policy(:system_user).index? %>
            <li class=<%= selected_page_tab == "user_management" ? "active" : "" %>>
              <%= link_to t("header.user_management"), user_management_root_path, :id => "user_management_link" %>
            </li>
          <% end %>

          <% if policy(:role).link? %>
            <li class=<%= selected_page_tab == "role_management" ? "active" : "" %>>
              <%= link_to t("header.role_management"), role_management_root_path, :id => "role_management_link" %>
            </li>
          <% end %>
          <% if policy(:audit_log).search? %>
            <li class=<%= selected_page_tab == "audit_log" ? "active" : "" %>>
              <%= link_to t("header.audit_log"), search_audit_logs_path, :id => "audit_log_link" %>
            </li>
          <% end %>
        </ul>
        <!-- end dropdown-menu-->

      </div>
      <!-- end projects dropdown -->

      <!-- pulled right: nav area -->
      <div class="pull-right">

        <!-- logout button -->
        <div id="logout" class="btn-header transparent pull-right">
          <span>
            <%= link_to(logout_path, :title => t("general.logout"), "data-action" => "userLogout", "data-action-yes" => t("logout_page.action_yes"), "data-action-no" => t("logout_page.action_no")) do %>
              <i class="fa fa-sign-out"></i>
            <% end %>
            <!--a href="login.html" title="Sign Out" data-action="userLogout" data-logout-msg="You can improve your security further after logging out by closing this opened browser"></a-->
          </span>
        </div>
        <!-- end logout button -->

        <!-- multiple lang dropdown : find all flags in the flags page -->
        <ul class="header-dropdown-list hidden-xs">
          <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag("blank.gif", :class => "flag flag-us") %>
              <span> English (US) </span> <i class="fa fa-angle-down"></i>
            </a>
            <ul class="dropdown-menu pull-right">
              <li class="active">
                <a href="javascript:void(0);">
                  <%= image_tag("blank.gif", :class => "flag flag-us", alt: "United States") %> English (US)
                </a>
              </li>
              <li>
                <a href="javascript:void(0);">
                  <%= image_tag("blank.gif", :class => "flag flag-cn", alt: "China") %> 中文
                </a>
              </li>
            </ul>
          </li>
        </ul>
        <!-- end multiple lang -->

        <!-- show user name -->
        <span class="navbar-text">
          <%= current_system_user.username %>
        </span>
        <!-- end show user name -->

      </div>
      <!-- end pulled right: nav area -->

    </header>

app/views/shared/_main_content.js.erb
$('div#content').css({ opacity: "0.0" }).html("<%= escape_javascript(render :file => @main_content, :formats => [ :html ] , :layout => nil) %>").delay(50).animate({ opacity: "1.0" }, 300)

app/views/shared/_main_panel.html.erb
    <!-- MAIN PANEL -->
		<div id="main" role="main">
			<!-- MAIN CONTENT -->
			<div id="content">
        <%= yield %>
			</div>
			<!-- END MAIN CONTENT -->
		</div>
		<!-- END MAIN PANEL -->

		<div id="flash_message" style="display: none;" data-message-type="">
		  <%= render partial: "shared/flash_message", flash: flash %>
		</div>

app/views/shared/_nav_setup.html.erb
<!-- activate left panel selected tab -->
<script>
  <% unless tab_to_activate.blank? %>
    $('nav li.active').removeClass("active");
  <% end %>

  $('#nav_<%= tab_to_activate %>').addClass("active");

</script>

app/views/shared/_pop_up_panel.html.erb
<div class="divMessageBox animated fadeOut fast" id="pop_up_dialog" style=" display: none;">
  <div class="ui-dialog" id="pop_up_ui_dialog" style="width: 600px; top: 50%; left: 50%; margin-top: -75px; margin-left: -300px;">
    <div id="pop_up_content" style="height: 60%; vertical-align: middle; padding: 20px; padding-bottom: 0px;" align="center">
    </div>
    <div id="pop_up_confirm_btn" align="center" style="margin-top: 10px; margin-bottom: 20px;">
      <table>
        <tr>
          <td><button id="cancel" class="btn btn-default"><%= t("general.cancel") %></button></td>
          <td width='20%'></td>
          <td><button id="confirm" class="btn btn-primary"><%= t("general.confirm") %></button></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<%= javascript_include_tag "popup.panel.js" %>