config/routes.rb
SsoRws::Application.routes.draw do
  devise_for :system_users, controllers: { :sessions => "system_user_sessions", :registration => "system_user_registrations" }, only: :sessions

  namespace :ldap do
    get :new
    post :login
  end

  namespace :saml do
    get :new
    post :acs
    get :metadata
    get :logout
  end

  namespace :gapi do
    get :new
    post :login
  end

  namespace :ldap_auth do
    get :new
    post :create
  end

  namespace :gapi_auth do
    get :new
    post :create
  end

  devise_scope :system_user do
    root :to => "system_user_sessions#new", :as => :app_root
    #root to: 'dashboard#home', :as => :home_root
    get "/login" => "system_user_sessions#new", :as => :login
    post '/login' => 'system_user_sessions#create'
    get "/logout" => "system_user_sessions#destroy", :as => :logout
    post "/passwords" => "system_user_registrations#update"
    get "/register" => "system_user_registrations#new", :as => :new_system_user_registration
    post "/register" => "system_user_registrations#create"
    get "/passwords" => "system_user_registrations#edit", :as => :edit_system_user_passwords
  end

  get "/app_login" => "internal/system_user_sessions#login"
  get "/app_logout" => "internal/system_user_sessions#logout"
  get "/ssrs_login" => "internal/system_user_sessions#ssrs_login"
  get "/second_authorize" => "internal/authorization#second_authorize"
  post "/user/get_info" => "internal/system_users#get_info"
  post "/user/validate_permission" => "internal/system_users#validate_permission"
  post "/usdm/login" => "internal/usdm_users#login"
  post "/usdm/get_info" => "internal/usdm_users#get_info"
  post "/usdm/validate_permission" => "internal/usdm_users#validate_permission"
  post "/usdm/change_password" => "internal/usdm_users#change_password"

  root :to => 'dashboard#home', :as => :root
  get 'home' => 'dashboard#home', :as => :home_root
  get 'user_management' => 'dashboard#user_management', :as => :user_management_root
  get 'role_management' => 'dashboard#role_management', :as => :role_management_root
  get 'domain_management' => 'dashboard#domain_management', :as => :domain_management_root

  resources :domains,  :except => [:destroy, :show]
  resources :domain_licensees, :only => [:index, :create] do
    collection do
      get 'get_casinos'
      post 'remove'
    end
  end

  get '/system_users/export' => 'system_users#export'
  get '/roles/export' => 'roles#export'
  get '/system_users/create_system_user_message' => 'system_users#create_system_user_message', as: :create_system_user_message
  resources :roles, :only => [:index, :show] do
    collection do
      post 'upload'
      post 'check_version'
    end
  end

  resources :system_users, :only => [:index, :show, :new, :create] do
    member do
      get 'edit_roles'
      post 'update_roles'
      post 'inactive'
    end
  end

  resources :change_logs, :only => [:index] do
    collection do
      get 'create_system_user'
      get 'inactive_system_user'
      get 'index_edit_role'
      get 'create_domain_licensee'
      get 'index_domain_ldap'
      get 'index_upload_role'
    end
  end

  resources :dashboard, :only => [:index] do
    collection do
      get 'home'
      get 'user_management'
      get 'role_management'
    end
  end

  resources :audit_logs, :only => [:show] do
    match 'search', :via => [:get, :post], on: :collection
  end

  resources :login_histories, :only => [:index]

  namespace :excels do
    get 'create_system_user_log'
    get 'login_history'
    get 'system_user_log'
  end

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

#  match "/404" => "errors#not_found"
  match "/401" => "application#handle_unauthorize"
#  match "/500" => "errors#exception"

  # Catch routing error here
  match '*unmatched', :to => 'application#handle_route_not_found', via: :get
end

app/controllers/system_user_registrations_controller.rb
class SystemUserRegistrationsController < ApplicationController
  layout "login"
  skip_before_filter :authenticate_system_user!, :check_activation_status
  rescue_from Exception, :with => :handle_fatal_error

  def new
    @nav_app_link = params[:app]
    #super
  end

  def create
    # begin
    #   [:success, :alert].each do |key|
    #     flash.delete(key)
    #   end
    #   @nav_app_link = params[:app]
    #   username_with_domain = params[:system_user][:username].downcase
    #   login = Rigi::Login.extract_login_name(username_with_domain)
    #   raise Rigi::InvalidLogin.new("alert.invalid_login") if login.nil?

    #   username = login[:username]
    #   domain = login[:domain]
    #   password = params[:system_user][:password]

    #   auth_source = SystemUser.validate_account!(username, domain)
    #   auth_source = auth_source.becomes(auth_source.auth_type.constantize)
    #   if auth_source.authenticate(username_with_domain, password)
    #     SystemUser.register_account!(username, domain)
    #     flash.now[:success] = "alert.signup_completed"
    #   else
    #     raise Rigi::InvalidLogin.new("alert.invalid_login")
    #   end
    # rescue Rigi::InvalidLogin, Rigi::InvalidUsername, Rigi::InvalidDomain
    #   Rails.logger.error "SystemUser[username=#{username_with_domain}] illegal login name format"
    #   flash.now[:alert] = "alert.invalid_login"
    # rescue Rigi::InvalidAuthSource => e
    #   Rails.logger.error "SystemUser[username=#{username_with_domain}] invalid domain - auth_source mapping"
    #   flash.now[:alert] = e.error_message
    # rescue Rigi::RegisteredAccount
    #   Rails.logger.error "SystemUser[username=#{username_with_domain}] register failed: {The account has been registered}"
    #   flash.now[:alert] = "alert.registered_account"
    # rescue Rigi::AccountNotInLdap
    #   Rails.logger.error "SystemUser[username=#{username_with_domain}] register failed: {Account is not in ldap server}"
    #   flash.now[:alert] = "alert.account_not_in_ldap"
    # rescue Rigi::AccountNoCasino
    #   Rails.logger.error "SystemUser[username=#{username_with_domain}] register failed: {Account no casino}"
    #   flash.now[:alert] = "alert.account_no_casino"
    # end

    # render :new
  end

  def edit
    @nav_app_link = params[:app]
    @app_name = params[:app_name]
  end

  def update
    @nav_app_link = params[:app]
    @app_name = params[:app_name]
    begin
      auth_source = find_auth_source
      check_new_password
      system_user = auth_source.change_password!(params[:system_user][:username], params[:system_user][:old_password], params[:system_user][:new_password])
      flash.now[:success] = I18n.t("success.reset_password")
    rescue Rigi::InvalidLogin, Rigi::InvalidDomain, Rigi::RemoteError => e
      Rails.logger.error "SystemUser[username=#{params[:system_user][:username]}] reset password failed: #{e.error_message}"
      flash.now[:alert] = e.error_message
    end
    render :edit
  end

  protected
  def check_new_password
    raise Rigi::InvalidLogin.new("password_page.new_password_tooltip") if params[:system_user][:new_password].blank?
    raise Rigi::InvalidLogin.new("password_page.confirm_password_fail") if params[:system_user][:new_password] != params[:system_user][:password_confirmation]
  end

  def find_auth_source
    domain = Domain.find_by_name(params[:system_user][:username].split('@')[1])
    raise Rigi::InvalidDomain.new('alert.invalid_domain') if !domain
    raise Rigi::InvalidDomain.new('alert.cannot_change_password') if domain.user_type != 'Usdm'
    domain.user_type.constantize.new
  end

  def handle_fatal_error(e)
    @from = params[:from]
    Rails.logger.error "#{e.message}"
    Rails.logger.error "#{e.backtrace.inspect}"

    respond_to do |format|
      format.html { render partial: "shared/error500", formats: [:html], layout: "error_page", status: :internal_server_error }
      format.js { render partial: "shared/error500", formats: [:js], status: :internal_server_error }
    end
    return
  end
end

app/views/system_user_registrations/edit.html.erb
<% content_for :header do %>
  <%= link_to(t("general.login"), @nav_app_link || app_login_path(app_name: @app_name), :class => "btn btn-danger") %>
<% end %>

<!-- ap_reset_password_panel -->
<%= form_for(:system_user, url: edit_system_user_passwords_path, html: {:id => "password_form", :class => "smart-form client-form"}) do |f| %>
  <header><%= t("title.reset_password_title") %></header>
  <fieldset>
    <section>
      <%= f.label(t("user.user_name"), :class => "label") %>
      <label class="input"> <i class="icon-append fa fa-user"></i>
        <%= f.text_field(:username, :placeholder => "email@example.com") %>
        <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <%=t("login_page.username_tooltip") %></b></label>
    </section>
    <section>
      <%= f.label(t("password_page.old_password"), :class => "label") %>
      <label class="input"> <i class="icon-append fa fa-lock"></i>
        <%= f.password_field :old_password, autocomplete: "new-password" %>
        <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> <%=t("password_page.password_tooltip") %></b> </label>
    </section>
    <section>
      <%= f.label(t("password_page.new_password"), :class => "label") %>
      <label class="input"> <i class="icon-append fa fa-lock"></i>
        <%= f.password_field :new_password %>
        <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> <%=t("password_page.new_password_tooltip") %></b> </label>
    </section>
    <section>
      <%= f.label(t("password_page.confirm_password"), :class => "label") %>
      <label class="input"> <i class="icon-append fa fa-lock"></i>
        <%= f.password_field :password_confirmation %>
        <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> <%=t("password_page.confirm_password_tooltip") %></b> </label>
    </section>
    <% if @nav_app_link.present? %>
      <%= hidden_field_tag "app", @nav_app_link %>
    <% end %>
    <% if @app_name.present? %>
      <%= hidden_field_tag "app_name", @app_name %>
    <% end %>
  </fieldset>
  <footer>
     <%= render :partial => "shared/caplock_reminder" %>
     <%= f.submit(t("password_page.update_password"), :class => "btn btn-primary") %>
  </footer>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
  $('#password_form').one('submit', function() {
      $(this).find('input[type="submit"]').attr('disabled','disabled');
  });
})
</script>

app/views/system_user_registrations/new.html.erb
<% content_for :header do %>
  <%= link_to(t("general.login"), @nav_app_link || login_path, :class => "btn btn-danger") %>
<% end %>

<!-- ap_register_panel -->
<%= form_for(:system_user, url: new_system_user_registration_path, html: {:class => "smart-form client-form"}) do |f| %>
  <header><%= t("title.signup_title") %></header>
  <fieldset>
    <section>
      <%= f.label(t("user.user_name"), :class => "label") %>
      <label class="input"> <i class="icon-append fa fa-user"></i>
        <%= f.text_field(:username, :placeholder => "email@example.com") %>
        <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <%=t("login_page.username_tooltip") %></b></label>
      
    </section>
    <section>
      <%= f.label(t("user.password"), :class => "label") %>
      <label class="input"> <i class="icon-append fa fa-lock"></i>
        <%= f.password_field :password %>
        <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> <%=t("login_page.password_tooltip") %></b> </label>
    </section>
    <% if @nav_app_link.present? %>
      <%= hidden_field_tag "app", @nav_app_link %>
    <% end %>
  </fieldset>
  <footer>
     <%= render :partial => "shared/caplock_reminder" %>
     <%= f.submit(t("general.sign_up"), :class => "btn btn-primary") %>
  </footer>
<% end %>