config/routes.rb
SsoRws::Application.routes.draw do
  devise_for :system_users, controllers: { :sessions => "system_user_sessions", :registration => "system_user_registrations" }, only: :sessions

  namespace :ldap do
    get :new
    post :login
  end

  namespace :saml do
    get :new
    post :acs
    get :metadata
    get :logout
  end

  namespace :gapi do
    get :new
    post :login
  end

  namespace :ldap_auth do
    get :new
    post :create
  end

  namespace :gapi_auth do
    get :new
    post :create
  end

  devise_scope :system_user do
    root :to => "system_user_sessions#new", :as => :app_root
    #root to: 'dashboard#home', :as => :home_root
    get "/login" => "system_user_sessions#new", :as => :login
    post '/login' => 'system_user_sessions#create'
    get "/logout" => "system_user_sessions#destroy", :as => :logout
    post "/passwords" => "system_user_registrations#update"
    get "/register" => "system_user_registrations#new", :as => :new_system_user_registration
    post "/register" => "system_user_registrations#create"
    get "/passwords" => "system_user_registrations#edit", :as => :edit_system_user_passwords
  end

  get "/app_login" => "internal/system_user_sessions#login"
  get "/app_logout" => "internal/system_user_sessions#logout"
  get "/ssrs_login" => "internal/system_user_sessions#ssrs_login"
  get "/second_authorize" => "internal/authorization#second_authorize"
  post "/user/get_info" => "internal/system_users#get_info"
  post "/user/validate_permission" => "internal/system_users#validate_permission"
  post "/usdm/login" => "internal/usdm_users#login"
  post "/usdm/get_info" => "internal/usdm_users#get_info"
  post "/usdm/validate_permission" => "internal/usdm_users#validate_permission"
  post "/usdm/change_password" => "internal/usdm_users#change_password"

  root :to => 'dashboard#home', :as => :root
  get 'home' => 'dashboard#home', :as => :home_root
  get 'user_management' => 'dashboard#user_management', :as => :user_management_root
  get 'role_management' => 'dashboard#role_management', :as => :role_management_root
  get 'domain_management' => 'dashboard#domain_management', :as => :domain_management_root

  resources :domains,  :except => [:destroy, :show]
  resources :domain_licensees, :only => [:index, :create] do
    collection do
      get 'get_casinos'
      post 'remove'
    end
  end

  get '/system_users/export' => 'system_users#export'
  get '/roles/export' => 'roles#export'
  get '/system_users/create_system_user_message' => 'system_users#create_system_user_message', as: :create_system_user_message
  resources :roles, :only => [:index, :show] do
    collection do
      post 'upload'
      post 'check_version'
    end
  end

  resources :system_users, :only => [:index, :show, :new, :create] do
    member do
      get 'edit_roles'
      post 'update_roles'
      post 'inactive'
    end
  end

  resources :change_logs, :only => [:index] do
    collection do
      get 'create_system_user'
      get 'inactive_system_user'
      get 'index_edit_role'
      get 'create_domain_licensee'
      get 'index_domain_ldap'
      get 'index_upload_role'
    end
  end

  resources :dashboard, :only => [:index] do
    collection do
      get 'home'
      get 'user_management'
      get 'role_management'
    end
  end

  resources :audit_logs, :only => [:show] do
    match 'search', :via => [:get, :post], on: :collection
  end

  resources :login_histories, :only => [:index]

  namespace :excels do
    get 'create_system_user_log'
    get 'login_history'
    get 'system_user_log'
  end

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

#  match "/404" => "errors#not_found"
  match "/401" => "application#handle_unauthorize"
#  match "/500" => "errors#exception"

  # Catch routing error here
  match '*unmatched', :to => 'application#handle_route_not_found', via: :get
end

app/controllers/internal/system_user_sessions_controller.rb
class Internal::SystemUserSessionsController < ApplicationController
  skip_before_filter :set_locale, :authenticate_system_user!, :check_activation_status, :verify_request_scope

  def login
    @app_name = params[:app_name]
    raise "app not found" unless @app_name
    auth_source = AuthSource.find_by_token(get_client_ip)
    if auth_source.nil?
      @error_info = { message: I18n.t("alert.bad_gateway_message"),
                      status: I18n.t("alert.bad_gateway_status"),
                      note: I18n.t("alert.unknown_token")}
      render layout: false, template: 'system_user_sessions/error_warning'
    else
      redirect_to auth_source.get_url(@app_name)
    end
  end

  def logout
    update_sign_out
    auth_source = AuthSource.find_by_token(get_client_ip)
    if auth_source.type.downcase == 'gapi'
      @app_name = params[:app_name]
      @g_clien_id = auth_source.auth_source_detail['data']['client_id']
      render layout: 'login', :template => "system_user_sessions/google_logout"
    else
      redirect_to "#{URL_BASE}/app_login?app_name=#{params[:app_name]}"
    end
  end

  def ssrs_login
    redirect_to "#{URL_BASE}/app_login?app_name=#{SSRS_APP_NAME}"
  end

  protected
  def update_sign_out
    return if params[:auth_token].blank?
    user_info = JWT.decode(params[:auth_token], 'test_key', true)[0]
    Rails.logger.info "token info: #{user_info}"
    LoginHistory.update_sign_out(user_info['id'], user_info['session_token'])
  rescue StandardError => e
    Rails.logger.error("logout decode auth token error: #{e.message} #{e.backtrace}")
  end
end

app/controllers/system_user_sessions_controller.rb
class SystemUserSessionsController < Devise::SessionsController
  layout "login"

  def new
    redirect_to "#{URL_BASE}/app_login?app_name=#{APP_NAME}"
  end

  def error_warning
    @error_info = params
    render layout: false
  end

  def create
    super
  end

  def destroy
    super
  end

  def after_sign_out_path_for(resource)
    auth_token = cookies[:user_management_token_info]
    cookies.delete(:user_management_token_info, domain: :all)
    "#{URL_BASE}/app_logout?app_name=#{APP_NAME}&auth_token=#{auth_token}"
  end
end

app/views/system_user_sessions/error_warning.html.erb
<!DOCTYPE html>
<html id="extr-page">
  <head>
    <%= render partial: "shared/login_head" %> 
  </head>
  
  <body class="animated fadeInDown">
  <header>
     <span id="extr-page-header-space">
     </span>
  </header>
    
  <div id="main" role="main">
    <!-- ap_main_content -->
    <div id="content" class="container">

      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="row">
            <div class="col-md-12">
              <div class="error-box text-center">
                <h1 class="error-text tada animated"><i class="fa fa-times-circle text-danger error-icon-shadow"></i> <%= @error_info[:status] %></h1>
                <h2 class="font-xl"><strong><%= t("general.product_portfolio") %> / <%= @app_name.titleize %></strong></h2>
                <h2 class="font-xl"><strong><%= @error_info[:message] %></strong></h2>
                <br />
                <p class="lead semi-bold">
                  <strong><%= @error_info[:note] %></strong>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
 
    </div>
  </div>
  </body>
</html>

app/views/system_user_sessions/google_logout.html.erb
<%= hidden_field_tag 'app_name', @app_name %>

<script type="text/javascript">
  $(document).ready(function() {
    function signOutGoogle() {
      gapi.load('auth2', function(){
        // Retrieve the singleton for the GoogleAuth library and set up the client.
        auth2 = gapi.auth2.init({
          client_id: '<%= @g_clien_id %>',
          // cookiepolicy: 'single_host_origin',
          cookiepolicy: 'none'
          // Request scopes in addition to 'profile' and 'email'
          // scope: 'custom'
        });
      });
      win = window.open("http://accounts.google.com/logout", "something", "width=550,height=570");
      signOutTimer(win)
    }

    function signOutTimer(win) {
      t = setTimeout(function(){
        console.log(gapi.auth2.getAuthInstance().isSignedIn.get())
        if(gapi.auth2.getAuthInstance().isSignedIn.get()){
          signOutTimer(win)
        } else {
          console.log('User signed out.')
          clearTimeout(t);
          win.close()
          window.location = "<%=URL_BASE%>/app_login?app_name=<%=@app_name%>"
        }
      }, 300);
    }

    signOutGoogle();
  });
</script>

app/views/system_user_sessions/google_new.html.erb
<!-- In the callback, you would hide the gSignInWrapper element on a
  successful sign in -->
<div id="gSignInWrapper" style="margin: 10px; text-align: center;">
  <div id="customBtn" class="customGPlusSignIn">
  </div>
</div>
<div style="margin: 10px;"><span id="error_msg"></span></div>
<%= hidden_field_tag 'app_name', @app_name %>

<script type="text/javascript">
  $(document).ready(function() {
    var googleUser = {};
    var username = '';
    var id_token = '';
    var startApp = function() {
      gapi.load('auth2', function(){
        // Retrieve the singleton for the GoogleAuth library and set up the client.
        auth2 = gapi.auth2.init({
          client_id: '<%= @g_clien_id %>',
          // cookiepolicy: 'single_host_origin',
          cookiepolicy: 'none'
          // Request scopes in addition to 'profile' and 'email'
          // scope: 'custom'
        });
        attachSignin(document.getElementById('customBtn'))
      });
    };

    function attachSignin(element) {
      auth2.attachClickHandler(element, {},
        function(googleUser) {
          var profile = googleUser.getBasicProfile();
          username = profile.getEmail()
          id_token = googleUser.getAuthResponse().id_token
          console.log(profile)
          signOutGoogle();
        }, function(error) {
          console.log(JSON.stringify(error, undefined, 2))
        }
      );
    }

    function signOutGoogle() {
      var auth2 = gapi.auth2.getAuthInstance();
      auth2.signOut().then(function () {
        console.log('User signed out.');
      });
      auth2.disconnect();
      loginSSO()
    }

    function loginSSO() {
      $.ajax({
        url: "/gapi/login",
        type: 'POST',
        dataType: 'json',
        data: {username: username, app_name: '<%= @app_name %>', id_token: id_token}
      }).done(function(rst) {
        console.log(rst)
        if(rst.error_code == 'OK'){
          window.location.href = rst.callback_url;
          console.log('login success')
        }else{
          $('#error_msg').html(rst.error_msg)
        }
      });
    }

    startApp();
  });
</script>

<style type="text/css">
  #customBtn {
    display: inline-block;
    /* background: white; */
    background: url('/assets/btn_google_signin_light_normal_web.png');
    color: #444;
    width: 190px;
    height: 44px;
    border-radius: 5px;
    border: thin solid #888;
    box-shadow: 1px 1px 1px grey;
    white-space: nowrap;
  }
  #customBtn:hover {
    cursor: pointer;
  }
</style>

app/views/system_user_sessions/ldap_new.html.erb
<% content_for :header do %>
  <%#= link_to(t("general.sign_up"), new_system_user_registration_path, :class => "btn btn-danger") %>
  <% if CAN_RESET_PASSWORD == 'true'%>
    <%= link_to(t("general.reset_password"), edit_system_user_passwords_path(app_name: @app_name), :class => "btn btn-danger") %>
  <% end %>
<% end %>

<!-- ap_login_panel -->
<%= form_for(:system_user, url: ldap_login_path, html: {:id => "login_form", :class => "smart-form client-form"}) do |f| %>
  <header><%= t("title.login_title") %></header>
  <fieldset>
    <section>
      <%= f.label(t("user.user_name"), :class => "label") %>
      <label class="input"><i class="icon-append fa fa-user"></i>
        <%= hidden_field_tag 'message_id', @message_id %>
        <%= hidden_field_tag 'app_name', @app_name %>
        <%= f.text_field(:username, :placeholder => "email@example.com") %>
        <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i><%=t("login_page.username_tooltip") %></b>
      </label>
    </section>
    <section>
      <%= f.label(t("user.password"), :class => "label") %>
      <label class="input"><i class="icon-append fa fa-lock"></i>
        <%= f.password_field :password %>
        <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i><%=t("login_page.password_tooltip") %></b>
      </label>
    </section>
  </fieldset>
  <footer>
      <%= render :partial => "shared/caplock_reminder" %>
      <%= f.submit(t("general.login"), :class => "btn btn-primary") %>
  </footer>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
  $('#login_form').one('submit', function() {
      $(this).find('input[type="submit"]').attr('disabled','disabled');
  });
})
</script>